stages:
  - test
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml

sast:
  stage: test

.deploy_job_template:
  image: ruby:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

deploy_heroku_production:
  extends: .deploy_job_template
  stage: deploy
  script:
    - dpl --provider=heroku --app=kiwano-frontend --api-key=$HEROKU_API_KEY
  environment:
    name: production
    url: https://kiwano-frontend.herokuapp.com/
  only:
    - main
